### ISSUE TITLE
deploy.sh should collect static files

### ISSUE THREAD

**Issue by agoncharov-reef** [reef-technologies/cookiecutter-rt-django#38]
```
docker-compose stop $SERVICES
docker-compose up -d

docker-compose exec -T app python manage.py collectstatic --no-input --clear   # <-----
docker-compose exec -T app python manage.py wait_for_database
docker-compose exec -T app python manage.py migrate
```

**Comment by mlech-reef** [comment]
We had this conversation with @ppolewicz and the outcome was that it sometimes makes sense when we use external storage for static files like DO Space or AWS S3, but by default, we use local Docker volume so that why collecting static files is part of the docker building process:

```
RUN ENV=prod SECRET_KEY=0 CSP_ENABLED= DATABASE_URL= python3 manage.py collectstatic --no-input --clear
```

I'm not super happy with this level of automation. It could be done better, but it's not that simple as you proposed.
